name = "blog-robotmk-org"
compatibility_date = "2024-01-01"

[env.production]
vars = { HUGO_VERSION = "0.124.1" }

[build]
command = "hugo --minify"
cwd = "."

[build.upload]
format = "directory"
dir = "public"

[site]
bucket = "./public"
